architecture: replication
auth:
  enabled: true
  existingSecret: bds-redis-auth
  existingSecretPasswordKey: redis-password
replica:
  replicaCount: 3
  persistence:
    size: 1Gi
sentinel:
  enabled: true
  quorum: 2
master:
  persistence:
    size: 1Gi
commonConfiguration: |-
  appendonly yes
  save 60 1000
resources:
  requests: { cpu: 50m, memory: 96Mi }
  limits: { cpu: 500m, memory: 256Mi }
