import { useEffect, useRef, useState } from 'react';
import * as maplibregl from 'maplibre-gl';
import type { GeoJSONSource, Map as MlMap } from 'maplibre-gl';
import maplibreWorkerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import 'maplibre-gl/dist/maplibre-gl.css';
import type { Listing } from '@/entities/listing/model/types';
export type MapBounds={minLat:number;maxLat:number;minLng:number;maxLng:number};
type MapMouseEvent = maplibregl.MapMouseEvent & { features?: GeoJSON.Feature[] };
maplibregl.setWorkerUrl(maplibreWorkerUrl);
const listingCollection=(items:Listing[]):GeoJSON.FeatureCollection=>({type:'FeatureCollection',features:items.filter(x=>x.publicLatitude!=null&&x.publicLongitude!=null).map(x=>({type:'Feature',properties:{id:x.id,title:x.title,address:x.addressSummary},geometry:{type:'Point',coordinates:[x.publicLongitude!,x.publicLatitude!]}}))});
export function ListingMap({listings,onSearchArea}:{listings:Listing[];onSearchArea:(b:MapBounds)=>void}){const host=useRef<HTMLDivElement>(null);const map=useRef<MlMap>();const listingsRef=useRef(listings);listingsRef.current=listings;const[bounds,setBounds]=useState<MapBounds>();
 useEffect(()=>{if(!host.current||map.current)return;const m=new maplibregl.Map({container:host.current,center:[105.82,21.03],zoom:10,style:'https://tiles.openfreemap.org/styles/positron'});map.current=m;m.addControl(new maplibregl.NavigationControl(),'top-right');m.on('load',()=>{m.addSource('listings',{type:'geojson',data:listingCollection(listingsRef.current),cluster:true,clusterMaxZoom:14,clusterRadius:50});m.addLayer({id:'clusters',type:'circle',source:'listings',filter:['has','point_count'],paint:{'circle-color':'#047857','circle-radius':['step',['get','point_count'],20,10,28,50,36],'circle-stroke-color':'#fff','circle-stroke-width':2}});m.addLayer({id:'cluster-count',type:'symbol',source:'listings',filter:['has','point_count'],layout:{'text-field':['get','point_count_abbreviated'],'text-size':12},paint:{'text-color':'#fff'}});m.addLayer({id:'points',type:'circle',source:'listings',filter:['!', ['has','point_count']],paint:{'circle-color':'#f59e0b','circle-radius':9,'circle-stroke-color':'#fff','circle-stroke-width':3}});m.on('click','clusters',async(e:MapMouseEvent)=>{const f=m.queryRenderedFeatures(e.point,{layers:['clusters']})[0];const z=await(m.getSource('listings')as GeoJSONSource).getClusterExpansionZoom(Number(f.properties?.cluster_id));m.easeTo({center:(f.geometry as GeoJSON.Point).coordinates as[number,number],zoom:z});});m.on('click','points',(e:MapMouseEvent)=>{const f=e.features?.[0];if(f)new maplibregl.Popup().setLngLat((f.geometry as GeoJSON.Point).coordinates as[number,number]).setText(String(f.properties?.title||'Tin đăng')).addTo(m);});});m.on('moveend',()=>{const b=m.getBounds();setBounds({minLat:b.getSouth(),maxLat:b.getNorth(),minLng:b.getWest(),maxLng:b.getEast()})});return()=>{m.remove();map.current=undefined}},[]);
 useEffect(()=>{const source=map.current?.getSource('listings') as GeoJSONSource|undefined;if(source)source.setData(listingCollection(listings))},[listings]);
 return <div className="absolute inset-0 z-30"><div ref={host} className="h-full w-full" aria-label="Bản đồ tin đăng tương tác"/><button disabled={!bounds} onClick={()=>bounds&&onSearchArea(bounds)} className="absolute top-4 left-1/2 -translate-x-1/2 min-h-11 px-5 rounded-full bg-white text-slate-900 font-bold shadow-xl border border-slate-200 disabled:opacity-60">Tìm trong khu vực này</button></div>}
