CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY, phone_lookup_hash VARCHAR(64) NOT NULL UNIQUE, phone_encrypted TEXT NOT NULL,
  full_name VARCHAR(150) NOT NULL, email VARCHAR(150) UNIQUE, password_hash VARCHAR(100), status VARCHAR(30) NOT NULL,
  email_verified_at TIMESTAMP WITH TIME ZONE,
  plan_code VARCHAR(30) NOT NULL DEFAULT 'FREE', plan_expires_at TIMESTAMP WITH TIME ZONE, listing_quota_remaining INT NOT NULL DEFAULT 2,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id UUID PRIMARY KEY, user_id UUID NOT NULL, token_hash VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL, used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS user_roles (user_id UUID NOT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY(user_id, role));
CREATE TABLE IF NOT EXISTS auth_sessions (
  id UUID PRIMARY KEY, user_id UUID NOT NULL, token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS audit_events (
  id UUID PRIMARY KEY, occurred_at TIMESTAMP WITH TIME ZONE NOT NULL, actor_id UUID, action VARCHAR(16) NOT NULL,
  resource VARCHAR(500) NOT NULL, result_status INT NOT NULL, client_fingerprint CHAR(64), previous_hash CHAR(64),
  event_hash CHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS api_idempotency_keys (
    scope VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    resource_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (scope, idempotency_key)
);
CREATE TABLE IF NOT EXISTS media_objects (
  object_key VARCHAR(80) PRIMARY KEY, owner_id UUID NOT NULL, content_type VARCHAR(40) NOT NULL,
  size_bytes BIGINT NOT NULL, visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC', created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
