import { useCallback, useEffect, useState } from 'react';
import { apiClient } from '@/shared/api/client';

interface Project { id:string; name:string; slug:string; developerName:string; provinceCode:string; districtCode:string; address:string; totalAreaM2:number; totalBlocks:number; totalUnits:number; handoverYear?:number; legalLicenseNumber?:string; status:string; createdAt:string; updatedAt:string }
const EMPTY = { name:'', developerName:'', provinceCode:'', districtCode:'', address:'', totalAreaM2:0, totalBlocks:0, totalUnits:0, handoverYear:'', legalLicenseNumber:'' };

export function ProjectCatalogPage() {
  const [items,setItems]=useState<Project[]>([]); const [keyword,setKeyword]=useState('');
  const [form,setForm]=useState(EMPTY); const [showForm,setShowForm]=useState(false);
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setItems(await apiClient<Project[]>(`/catalog/projects${keyword.trim()?`?keyword=${encodeURIComponent(keyword.trim())}`:''}`))}catch{setItems([]);setError('Không thể tải danh mục dự án từ máy chủ.')}finally{setLoading(false)}},[keyword]);
  useEffect(()=>{void load()},[load]);
  const create=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const created=await apiClient<Project>('/catalog/projects',{method:'POST',body:JSON.stringify({...form,handoverYear:form.handoverYear?Number(form.handoverYear):null})});setItems(current=>[created,...current]);setForm(EMPTY);setShowForm(false)}catch{setError('Không thể tạo dự án; dữ liệu chưa được lưu.')}finally{setBusy(false)}};
  const labels={name:'Tên dự án',developerName:'Chủ đầu tư',provinceCode:'Mã tỉnh/thành',districtCode:'Mã quận/huyện',address:'Địa chỉ',totalAreaM2:'Tổng diện tích m²',totalBlocks:'Số khối',totalUnits:'Số căn',handoverYear:'Năm bàn giao',legalLicenseNumber:'Số giấy phép pháp lý'};
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-10">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">Danh mục dự án</h1><p className="mt-1 text-slate-600">Dữ liệu được đọc và ghi trực tiếp qua API dự án.</p></div><button type="button" onClick={()=>setShowForm(true)} className="min-h-11 rounded-xl bg-primary px-5 font-bold text-white">Tạo dự án</button></header>
    <form onSubmit={event=>{event.preventDefault();void load()}} className="flex gap-2"><input value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="Tìm theo tên dự án" className="min-h-11 flex-1 rounded-xl border px-4"/><button className="min-h-11 rounded-xl border px-5 font-bold">Tìm</button></form>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-800">{error}</p>}
    {loading?<p role="status">Đang tải dự án…</p>:items.length===0?<p className="rounded-xl bg-slate-50 p-8 text-center text-slate-600">Chưa có dự án phù hợp.</p>:<section className="grid gap-4 md:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><h2 className="text-lg font-bold">{item.name}</h2><span className="text-xs font-bold text-slate-500">{item.status}</span></div><p className="mt-1 text-sm text-slate-600">{item.developerName}</p><p className="mt-3 text-sm">{item.address||'Chưa cung cấp địa chỉ'}</p><p className="mt-3 text-sm">{item.totalAreaM2.toLocaleString('vi-VN')} m² · {item.totalBlocks} khối · {item.totalUnits} căn</p><p className="mt-4 text-xs text-slate-500">Cập nhật: {new Date(item.updatedAt).toLocaleString('vi-VN')}</p></article>)}</section>}
    {showForm&&<div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/60 p-4" role="dialog" aria-modal="true"><form onSubmit={create} className="grid w-full max-w-2xl gap-3 rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Tạo dự án mới</h2>{(Object.keys(labels) as Array<keyof typeof labels>).map(key=><label key={key} className="text-sm font-semibold">{labels[key]}<input required={!['handoverYear','legalLicenseNumber'].includes(key)} type={['totalAreaM2','totalBlocks','totalUnits','handoverYear'].includes(key)?'number':'text'} value={form[key]} onChange={event=>setForm({...form,[key]:['totalAreaM2','totalBlocks','totalUnits'].includes(key)?Number(event.target.value):event.target.value})} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label>)}<div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowForm(false)} className="min-h-11 rounded-lg border px-4">Hủy</button><button disabled={busy} className="min-h-11 rounded-lg bg-primary px-5 font-bold text-white disabled:opacity-50">{busy?'Đang lưu…':'Lưu dự án'}</button></div></form></div>}
  </main>;
}
export default ProjectCatalogPage;
