import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, RefreshCw, Search, X } from 'lucide-react';
import { apiClient } from '@/shared/api/client';

type Order = { id:string; customerName:string; customerEmail:string; planName:string; amountVnd:number; reference:string; status:string; createdAt:string; reportedAt?:string|null; reviewedAt?:string|null; reviewNote?:string|null };
type Page = { items:Order[]; page:number; size:number; total:number };
type Bank = { bankBin:string; bankName:string; accountNumber:string; accountName:string; adminEmail:string; version:number };
const labels:Record<string,string>={CREATED:'Chờ chuyển khoản',TRANSFER_REPORTED:'Chờ đối soát',APPROVED:'Đã xác nhận',REJECTED:'Từ chối',CANCELLED:'Đã hủy'};
const format = (value:string) => new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));

export function AdminBillingPage(){
  const [data,setData]=useState<Page>({items:[],page:0,size:20,total:0}); const [bank,setBank]=useState<Bank>({bankBin:'',bankName:'',accountNumber:'',accountName:'',adminEmail:'',version:0});
  const [status,setStatus]=useState('TRANSFER_REPORTED'); const [query,setQuery]=useState(''); const [appliedQuery,setAppliedQuery]=useState(''); const [notice,setNotice]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState<string|null>(null); const [reasons,setReasons]=useState<Record<string,string>>({});
  const load=async(page=data.page)=>{setError('');try{const [orders,nextBank]=await Promise.all([apiClient<Page>(`/billing/admin/orders?page=${page}&size=20&status=${encodeURIComponent(status)}&q=${encodeURIComponent(appliedQuery)}`),apiClient<Bank>('/billing/admin/bank')]);setData(orders);if(nextBank)setBank(nextBank)}catch(e){setError(e instanceof Error?e.message:'Không thể tải dữ liệu đối soát.')}};
  useEffect(()=>{void load(0)},[status,appliedQuery]);
  const pending=data.items.filter(x=>x.status==='TRANSFER_REPORTED').length; const pages=Math.max(1,Math.ceil(data.total/data.size)); const summary=useMemo(()=>`${data.total} đơn hàng${status?' theo trạng thái đã chọn':''}`,[data.total,status]);
  const review=async(id:string,approved:boolean)=>{const reason=reasons[id]?.trim();if(!approved&&!reason){setError('Nhập lý do trước khi từ chối đơn hàng.');return}setBusy(id);setNotice('');setError('');try{await apiClient(`/billing/admin/reconciliation/${id}/${approved?'approve':'reject'}`,{method:'POST',body:JSON.stringify(approved?{note:'Đã kiểm tra sao kê thủ công'}:{reason})});setNotice(approved?'Đã xác nhận thanh toán và cấp gói cho khách hàng.':'Đã từ chối và gửi lý do cho khách hàng.');await load()}catch(e){setError(e instanceof Error?e.message:'Không thể cập nhật đơn hàng.')}finally{setBusy(null)}};
  const saveBank=async()=>{setBusy('bank');setNotice('');setError('');try{await apiClient('/billing/admin/bank',{method:'PUT',body:JSON.stringify(bank)});setNotice('Đã lưu tài khoản nhận tiền và mã VietQR mới.');await load()}catch(e){setError(e instanceof Error?e.message:'Không thể lưu tài khoản ngân hàng.')}finally{setBusy(null)}};
  return <section className="mx-auto max-w-7xl p-4 sm:p-6 lg:p-8 space-y-6"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-bold text-slate-950">Đơn hàng & đối soát</h2><p className="mt-1 text-sm text-slate-600">VietQR chỉ tạo mã chuyển khoản. Bạn kiểm tra sao kê và xác nhận từng đơn tại đây.</p></div><button type="button" onClick={()=>void load()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold text-slate-700 hover:bg-slate-50"><RefreshCw className="h-4 w-4"/>Làm mới</button></header>
    {notice&&<p role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{notice}</p>}{error&&<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-900">{error}</p>}
    <section className="rounded-xl bg-white p-5 shadow-sm"><h3 className="text-base font-bold text-slate-950">Tài khoản nhận chuyển khoản</h3><p className="mt-1 text-sm text-slate-600">Thông tin này được dùng để sinh mã VietQR cho đơn mới.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{([['bankBin','BIN ngân hàng'],['bankName','Tên ngân hàng'],['accountNumber','Số tài khoản'],['accountName','Tên chủ tài khoản'],['adminEmail','Email báo đơn chờ']] as const).map(([key,label])=><label key={key} className="text-xs font-semibold text-slate-700">{label}<input value={bank[key]||''} onChange={e=>setBank({...bank,[key]:e.target.value})} className="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm font-normal text-slate-950 outline-none focus:border-primary focus:ring-2 focus:ring-primary/20"/></label>)}</div><button type="button" disabled={busy!==null} onClick={()=>void saveBank()} className="mt-4 min-h-11 rounded-lg bg-primary px-4 text-sm font-bold text-white hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-60">Lưu tài khoản nhận tiền</button></section>
    <section className="rounded-xl bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 lg:flex-row lg:items-center lg:justify-between"><div><h3 className="font-bold text-slate-950">Danh sách đơn hàng</h3><p className="mt-1 text-sm text-slate-600">{summary}{pending>0&&` · ${pending} đơn cần xử lý trên trang này`}</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="flex min-h-11 items-center gap-2 rounded-lg border border-slate-300 px-3 text-sm text-slate-500"><Search className="h-4 w-4"/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')setAppliedQuery(query)}} placeholder="Mã đơn, tên hoặc email" className="w-full bg-transparent text-slate-950 outline-none sm:w-52"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="min-h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm font-medium text-slate-800"><option value="">Tất cả trạng thái</option>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={()=>setAppliedQuery(query)} className="min-h-11 rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white">Tìm</button></div></div>
      <div className="overflow-x-auto"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Khách hàng</th><th className="px-5 py-3">Gói / số tiền</th><th className="px-5 py-3">Mã chuyển khoản</th><th className="px-5 py-3">Trạng thái</th><th className="px-5 py-3">Thời gian</th><th className="px-5 py-3">Xử lý</th></tr></thead><tbody className="divide-y divide-slate-100">{data.items.map(order=><tr key={order.id} className="align-top"><td className="px-5 py-4 font-semibold text-slate-900">{order.customerName}<span className="mt-0.5 block font-normal text-slate-500">{order.customerEmail}</span></td><td className="px-5 py-4 text-slate-800">{order.planName}<span className="mt-0.5 block font-semibold text-slate-950">{order.amountVnd.toLocaleString('vi-VN')}đ</span></td><td className="px-5 py-4 font-mono text-xs font-semibold text-primary">{order.reference}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{labels[order.status]||order.status}</span>{order.reviewNote&&<span className="mt-1 block max-w-52 text-xs text-slate-500">{order.reviewNote}</span>}</td><td className="px-5 py-4 text-slate-600">Tạo: {format(order.createdAt)}{order.reportedAt&&<span className="mt-1 block">Báo CK: {format(order.reportedAt)}</span>}</td><td className="px-5 py-4">{order.status==='TRANSFER_REPORTED'?<div className="flex min-w-52 flex-col gap-2"><div className="flex gap-2"><button disabled={busy!==null} onClick={()=>void review(order.id,true)} className="inline-flex min-h-9 items-center gap-1 rounded-lg bg-emerald-700 px-3 text-xs font-bold text-white disabled:opacity-60"><Check className="h-3.5 w-3.5"/>Xác nhận</button><button disabled={busy!==null} onClick={()=>void review(order.id,false)} className="inline-flex min-h-9 items-center gap-1 rounded-lg border border-rose-300 px-3 text-xs font-bold text-rose-700 disabled:opacity-60"><X className="h-3.5 w-3.5"/>Từ chối</button></div><input value={reasons[order.id]||''} onChange={e=>setReasons({...reasons,[order.id]:e.target.value})} placeholder="Lý do nếu từ chối" className="min-h-9 rounded-lg border border-slate-300 px-2 text-xs outline-none focus:border-primary"/></div>:<span className="text-xs text-slate-500">Không cần thao tác</span>}</td></tr>)}{data.items.length===0&&<tr><td colSpan={6} className="px-5 py-14 text-center text-sm text-slate-500">Chưa có đơn hàng phù hợp. Hãy đổi bộ lọc hoặc làm mới dữ liệu.</td></tr>}</tbody></table></div>
      <footer className="flex items-center justify-between border-t border-slate-200 px-5 py-3 text-sm text-slate-600"><span>Trang {data.page+1}/{pages}</span><div className="flex gap-2"><button type="button" disabled={data.page===0} onClick={()=>void load(data.page-1)} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-300 disabled:opacity-40" aria-label="Trang trước"><ChevronLeft className="h-4 w-4"/></button><button type="button" disabled={data.page+1>=pages} onClick={()=>void load(data.page+1)} className="grid h-9 w-9 place-items-center rounded-lg border border-slate-300 disabled:opacity-40" aria-label="Trang sau"><ChevronRight className="h-4 w-4"/></button></div></footer></section></section>;
}
export default AdminBillingPage;
