import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, EyeOff, RefreshCw, XCircle } from 'lucide-react';
import { dismissReport, emergencyHideListing, fetchLeads, fetchReports, resolveReport, updateLeadStatus } from '@/entities/lead/api/leadApi';
import type { LeadItem, ListingReport, LeadStatus } from '@/entities/lead/model/types';
import { Button } from '@/shared/ui/Button';

const REPORT_LABELS: Record<ListingReport['status'], string> = { PENDING: 'Chờ xử lý', WAITING_REPLY: 'Chờ phản hồi', RESOLVED: 'Đã giải quyết', DISMISSED: 'Đã bác bỏ', APPEALED: 'Có khiếu nại' };
const LEAD_LABELS: Record<LeadStatus, string> = { NEW: 'Mới', CONTACTED: 'Đã liên hệ', APPOINTED: 'Đã hẹn', CLOSED: 'Đã đóng', SPAM: 'Spam' };

export default function LeadsAndReportsPage() {
  const [reports, setReports] = useState<ListingReport[]>([]); const [leads, setLeads] = useState<LeadItem[]>([]);
  const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState('');
  const [notes, setNotes] = useState<Record<string, string>>({}); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [r, l] = await Promise.all([fetchReports(), fetchLeads()]); setReports(r); setLeads(l); } catch { setError('Không thể tải dữ liệu. Kiểm tra kết nối rồi thử lại.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const act = async (report: ListingReport, action: 'hide'|'resolve'|'dismiss') => { const note = notes[report.id]?.trim() ?? ''; if (!note) { setError(`Nhập ghi chú xử lý cho vụ việc #${report.caseNumber}.`); return; } setBusyId(report.id); setError(''); try { if (action === 'hide') await emergencyHideListing(report.id, note); if (action === 'resolve') await resolveReport(report.id, note, false); if (action === 'dismiss') await dismissReport(report.id, note, true); setNotes(x => ({ ...x, [report.id]: '' })); await load(); } catch { setError(`Không thể cập nhật vụ việc #${report.caseNumber}. Dữ liệu máy chủ chưa thay đổi.`); } finally { setBusyId(''); } };
  const changeLead = async (id: string, status: LeadStatus) => { setBusyId(id); setError(''); try { await updateLeadStatus(id, status); await load(); } catch { setError('Không thể cập nhật trạng thái lead. Vui lòng thử lại.'); } finally { setBusyId(''); } };
  return <main className="mx-auto max-w-6xl px-4 py-10"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold">Lead và báo xấu</h1><p className="mt-1 text-slate-600">Dữ liệu vận hành và quyết định xử lý được ghi trực tiếp về máy chủ.</p></div><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className="mr-2 h-4 w-4" />Tải lại</Button></header>
    {error && <div className="mt-6 flex items-start gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-800" role="alert"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0" /><span>{error}</span></div>}{loading && <p className="mt-8" role="status">Đang tải dữ liệu…</p>}
    {!loading && <div className="mt-8 grid items-start gap-6 lg:grid-cols-2"><section className="min-w-0 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Báo xấu ({reports.length})</h2>{reports.length === 0 ? <p className="mt-5 text-slate-500">Chưa có báo xấu cần xử lý.</p> : <div className="mt-4 divide-y">{reports.map(report => { const actionable = ['PENDING','WAITING_REPLY','APPEALED'].includes(report.status); return <article key={report.id} className="py-5"><div className="flex flex-wrap justify-between gap-3"><strong className="break-all">#{report.caseNumber}</strong><span className="text-sm font-semibold text-slate-600">{REPORT_LABELS[report.status]}</span></div><p className="mt-2 break-words text-sm">{report.description}</p><p className="mt-2 text-xs text-slate-500">Tin {report.listingId.slice(0,8)} · {new Intl.DateTimeFormat('vi-VN',{dateStyle:'short',timeStyle:'short'}).format(new Date(report.createdAt))}</p>{report.resolutionNote && <p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm"><strong>Ghi chú:</strong> {report.resolutionNote}</p>}{actionable && <div className="mt-4"><label htmlFor={`note-${report.id}`} className="text-sm font-semibold">Ghi chú xử lý *</label><textarea id={`note-${report.id}`} maxLength={1000} value={notes[report.id] ?? ''} onChange={e => setNotes(x => ({...x,[report.id]:e.target.value}))} className="mt-1 min-h-24 w-full rounded-xl border px-3 py-2 text-base" placeholder="Nêu căn cứ cho quyết định để lưu vết kiểm tra"/><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" disabled={busyId===report.id} onClick={() => void act(report,'hide')}><EyeOff className="mr-1 h-4 w-4"/>Tạm ẩn tin</Button><Button disabled={busyId===report.id} onClick={() => void act(report,'resolve')}><CheckCircle2 className="mr-1 h-4 w-4"/>Giải quyết</Button><Button variant="outline" disabled={busyId===report.id} onClick={() => void act(report,'dismiss')}><XCircle className="mr-1 h-4 w-4"/>Bác bỏ</Button></div></div>}</article>})}</div>}</section>
      <section className="min-w-0 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Lead ({leads.length})</h2>{leads.length===0 ? <p className="mt-5 text-slate-500">Chưa có lead.</p> : <div className="mt-4 divide-y">{leads.map(lead => <article key={lead.id} className="py-4"><strong className="break-words">{lead.fullName}</strong><p className="break-words text-sm text-slate-600">{lead.maskedPhone}{lead.note?` · ${lead.note}`:''}</p><select aria-label={`Trạng thái lead ${lead.fullName}`} disabled={busyId===lead.id} value={lead.status} onChange={e => void changeLead(lead.id,e.target.value as LeadStatus)} className="mt-2 min-h-11 rounded-lg border bg-white px-3 py-2 text-base">{Object.entries(LEAD_LABELS).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></article>)}</div>}</section></div>}
  </main>;
}
