import { useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { CheckCircle2, Lock } from 'lucide-react';
import { apiClient } from '@/shared/api/client';

export function ResetPasswordPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const token = params.get('token') ?? '';
  const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [done, setDone] = useState(false);
  const validToken = useMemo(() => token.length >= 32, [token]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(''); if (password.length < 10) { setError('Mật khẩu cần tối thiểu 10 ký tự.'); return; } if (password !== confirmation) { setError('Xác nhận mật khẩu không khớp.'); return; } setSaving(true); try { await apiClient('/auth/reset-password', { method: 'POST', body: JSON.stringify({ token, password }) }); setDone(true); } catch { setError('Liên kết không hợp lệ hoặc đã hết hạn. Hãy yêu cầu một liên kết mới.'); } finally { setSaving(false); } };
  if (!validToken) return <main className="mx-auto max-w-md px-4 py-12"><p className="rounded-xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800">Liên kết đặt lại mật khẩu không hợp lệ. <Link to="/forgot-password" className="font-bold underline">Yêu cầu liên kết mới</Link></p></main>;
  return <main className="mx-auto max-w-md px-4 py-12"><section className="rounded-2xl border border-outline-variant/50 bg-surface-container-lowest p-6 md:p-8"><Lock className="h-8 w-8 text-primary" /><h1 className="mt-4 text-2xl font-bold text-on-surface">Đặt mật khẩu mới</h1>{done ? <div className="mt-5 text-sm text-on-surface-variant"><CheckCircle2 className="h-8 w-8 text-emerald-700" /><p className="mt-3">Mật khẩu đã được thay đổi. Các phiên đăng nhập cũ đã được đăng xuất.</p><button onClick={() => navigate('/')} className="mt-5 font-semibold text-primary hover:underline">Đến đăng nhập</button></div> : <form onSubmit={submit} className="mt-5 space-y-4"><p className="text-sm text-on-surface-variant">Tạo mật khẩu mới tối thiểu 10 ký tự.</p><label className="grid gap-2 text-sm font-semibold">Mật khẩu mới<input required minLength={10} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} className="min-h-11 rounded-lg border border-outline-variant px-3 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/15" /></label><label className="grid gap-2 text-sm font-semibold">Xác nhận mật khẩu<input required type="password" autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="min-h-11 rounded-lg border border-outline-variant px-3 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/15" /></label>{error && <p role="alert" className="text-sm text-rose-700">{error}</p>}<button disabled={saving} className="min-h-11 rounded-lg bg-primary px-5 text-sm font-bold text-white disabled:opacity-60">{saving ? 'Đang đổi mật khẩu…' : 'Đổi mật khẩu'}</button></form>}</section></main>;
}

export default ResetPasswordPage;
